CREATE TABLE IF NOT EXISTS accounts(
  id VARCHAR(255) NOT NULL PRIMARY KEY COMMENT 'primary key',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT 'Time Created',
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Last Update',
  name VARCHAR(255) COMMENT 'User Name',
  email VARCHAR(255) UNIQUE COMMENT 'User Email',
  picture VARCHAR(255) COMMENT 'User Picture'
) default charset utf8mb4 COMMENT '';

CREATE TABLE IF NOT EXISTS pictures(
  id INT NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT 'primary key',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT 'Time Created',
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Last Update',
  img_url VARCHAR(255) COMMENT 'Picture URL',
  album_id INT NOT NULL COMMENT 'Album ID',
creator_id VARCHAR(255) NOT NULL COMMENT 'Creator ID',
  FOREIGN KEY (creator_id) REFERENCES accounts(id) ON DELETE CASCADE ,
  FOREIGN KEY (album_id) REFERENCES albums(id) ON DELETE CASCADE
)

CREATE TABLE IF NOT EXISTS albums(
 id INT NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT 'primary key',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT 'Time Created',
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Last Update',
  title VARCHAR(255) NOT NULL COMMENT 'Album Name',
description TEXT COMMENT 'Album Description',
archived BOOLEAN NOT NULL DEFAULT false,
category ENUM(
    'aesthetics',
    'games',
    'animals',
    'food',
    'vibes',
    'misc'
),
cover_img TEXT NOT NULL COMMENT 'Cover Image',
creator_id VARCHAR(255) NOT NULL COMMENT 'Creator ID',
  FOREIGN KEY (creator_id) REFERENCES accounts(id) ON DELETE CASCADE
)

DROP TABLE watchers;
DROP TABLE pictures;
DROP TABLE albums;


 CREATE TABLE watchers( 
   id INT NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT 'primary key',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT 'Time Created',
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Last Update',
account_id VARCHAR(255) NOT NULL,
album_id INT NOT NULL,
  FOREIGN KEY (account_id) REFERENCES accounts(id) ON DELETE CASCADE ,
  FOREIGN KEY (album_id) REFERENCES albums(id) ON DELETE CASCADE,
  UNIQUE (account_id, album_id)
 )
